### ISSUE TITLE
Gros bug affectant la requette des scenario

### ISSUE THREAD

**Issue by danielrubango** [QuanticDrone/mad-doctor#16]
Ce problème arrive lorsque l'on est en plein début de scenario hebdomadaire et que l'on passait à un nouveau mois, la requête demandant des données à la base de données échoue ou renvoie NULL puisqu'il se dit qu'aujourd'hui c'est un nouveau mois, alors, rechercher les scénarios correspondant à ce nouveaux mois, comme il n'en trouve pas, il revoie ce NULL... 

Je vais essayer de le corriger en cherchant à savoir pourquoi il fait mail ses calculs.

**Comment by danielrubango** [comment]
Ah, oui, la variable mois-courant qui ce base da la journée courante, c'est elle qui fait en sorte que c'est soit le mois qui vient de commencer qui soit choisie pourtant nous somme au bon milieu d'un scénario hebdomadaire du mois précédent.

**Comment by danielrubango** [comment]
Problème résolu.

**Comment by hervinhio** [comment]
Une semaine devrait rester une semaine car le début du mois ne marque pas toujours le début d'une nouvelle semaine.
