### ISSUE TITLE
Scenario id not returned in the JSON response.

### ISSUE THREAD

**Issue by hervinhio** [QuanticDrone/mad-doctor#23]
Le champs id devrait être renvoyé pour chaque scénario. Ceci me permet de faire un calcul descendant cummulatif pour les rubriques.

**Comment by hervinhio** [comment]
Aucune solution?

**Comment by danielrubango** [comment]
Je m'en occupe tout de suite...

**Comment by danielrubango** [comment]
C'est bon, je crois, j'envoie maintenant les id des scenarios correspondant.

**Comment by hervinhio** [comment]
Merci Daniel.
